import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const linkClass = "bg-slate-100 p-[7px] rounded-[5px]";
  return (
    <html lang="en">
      <body className="p-[20px]">
        <nav className="flex items-center gap-[5rem] mb-[50px]">
          <Link href="/" className={linkClass}>
            Home
          </Link>
          <Link href="/products" className={linkClass}>
            /product
          </Link>
          <Link href="/products/id" className={linkClass}>
            /product/[id]
          </Link>
          <Link href="/products/info/123/abc" className={linkClass}>
            /product/[...info]
          </Link>
          <Link href="/dashboard" className={linkClass}>
            /dashboard
          </Link>
          <Link href="/dashboard/info" className={linkClass}>
            error page
          </Link>
          <Link href="/nottttfound" className={linkClass}>
            NotFound page
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
